// src/settings/components/m-tab-bar.vue
<template>
  <div class="mdc-tab-bar" role="tablist" @MDCTabBar:activated="onActivated">
    <div class="mdc-tab-scroller">
      <div class="mdc-tab-scroller__scroll-area">
        <div class="mdc-tab-scroller__scroll-content">
          <m-tab v-for="(tab, index) in tabs" :key="index" :id="tab.id">
            <template slot="icon">{{ tab.icon }}</template>
            {{ tab.id }}
          </m-tab>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import {MDCTabBar} from '@material/tab-bar/index'
import MTab from './m-tab.vue'

export default {
  name: 'm-tab-bar',
  props: {
    activeTabId: {
      type: Number,
      default: 0,
    },
    tabs: {
      type: Array,
      default: [],
    },
  },
  components: {MTab},
  mounted() {
    this.mdcTabBar = MDCTabBar.attachTo(this.$el)
    this.mdcTabBar.activateTab(this.activeTabId)
  },
  beforeDestroy() {
    this.mdcTabBar.destroy()
  },
  methods: {
    onActivated(e) {
      this.$emit('activated', e.detail.index)
    },
  },
}
</script>

<style lang="scss">
@import '~@material/tab-bar/mdc-tab-bar';
@import '~@material/tab-scroller/mdc-tab-scroller';
@import '~@material/tab-indicator/mdc-tab-indicator';
@import '~@material/tab/mdc-tab';
</style>

// src/settings/solid-js/m-tab-bar.tsx
import {For} from 'solid-js'

export interface IPageTab {
  id: string
  icon: string
}

interface IMTabBarProps {
  tabs: IPageTab[]
  onTabActivated: (tabId: string) => void
}

export function MTabBar(props: IMTabBarProps) {
  // const {store} = createMTabBarStore(props)
  return (
    // <div class="mdc-tab-bar" role="tablist" @MDCTabBar:activated="onActivated">
    <div class="mdc-tab-bar" role="tablist">
      <div class="mdc-tab-scroller">
        <div class="mdc-tab-scroller__scroll-area">
          <div class="mdc-tab-scroller__scroll-content">
            {/* // <m-tab v-for="(tab, index) in tabs" :key="index" :id="tab.id"> */}
            {/* // <template slot="icon">{{ tab.icon }}</template> */}
            {/* </m-tab> */}
            <For each={props.tabs}>
              {(tab) => (
                <button
                  class="mdc-tab"
                  role="tab"
                  aria-selected="true"
                  tabindex="0"
                  data-test="id"
                  onClick={() => {
                    props.onTabActivated(tab.id)
                  }}
                >
                  <span class="mdc-tab__content">
                    <span class="mdc-tab__icon material-icons" aria-hidden="true">
                      {/* <slot name="icon"></slot> */}
                      {tab.icon}
                    </span>
                    <span class="mdc-tab__text-label">
                      {/* <slot></slot> */}
                      {tab.id}
                    </span>
                  </span>
                  <span class="mdc-tab-indicator">
                    <span class="mdc-tab-indicator__content mdc-tab-indicator__content--underline"></span>
                  </span>
                  <span class="mdc-tab__ripple"></span>
                </button>
              )}
            </For>
          </div>
        </div>
      </div>
    </div>
  )
}
