// src/settings/solid-js/components/m-button/m-button.tsx
import {Show} from 'solid-js/web'
import {onMount} from 'solid-js'
// eslint-disable-next-line import/no-extraneous-dependencies
import {MDCRipple} from '@material/ripple/index'
import styles from './m-button.module.scss'

interface IProps {
  raised?: boolean
  unelevated?: boolean
  outlined?: boolean
  href?: string
  target?: string
  icon?: string
  text: string
  onClick?: () => void
}

export function MButton(props: IProps) {
  let buttonElement: HTMLElement
  onMount(() => {
    MDCRipple.attachTo(buttonElement!)
  })
  return (
    <Show when={props.href} fallback={<MButtonWithIcon {...props} ref={buttonElement!} />}>
      <MHyperlinkButton {...props} ref={buttonElement!} />
    </Show>
  )
}

interface IPropsWithRef extends IProps {
  ref: HTMLElement
}

function MHyperlinkButton(props: IPropsWithRef) {
  return (
    <a
      ref={props.ref as HTMLAnchorElement}
      // the mdc-button class is needed to preserve ripple effect
      class={`mdc-button ${styles.button}`}
      classList={{
        [styles.buttonRaised]: props.raised,
        [styles.buttonUnelevated]: props.unelevated,
        [styles.buttonOutlined]: props.outlined,
      }}
      href={props.href}
      role="button"
      onClick={props.onClick}
    >
      <i class={styles.icon}>{props.icon}</i>
      {props.text}
    </a>
  )
}

function MButtonWithIcon(props: IPropsWithRef) {
  return (
    <button
      ref={props.ref as HTMLButtonElement}
      class={`mdc-button ${styles.button}`}
      classList={{
        [styles.buttonRaised]: props.raised,
        [styles.buttonUnelevated]: props.unelevated,
        [styles.buttonOutlined]: props.outlined,
      }}
      onClick={(event) => {
        event.preventDefault()
        props.onClick?.()
      }}
    >
      <i class={styles.icon}>{props.icon}</i>
      {props.text}
    </button>
  )
}

// src/settings/components/MButton.vue
<template>
  <a
    v-if="href"
    :class="classes"
    :href="href"
    v-bind="$attrs"
    role="button"
    class="mdc-button"
    v-on="$listeners"
  >
    <slot name="icon"/>
    <slot/>
  </a>
  <button
    v-else
    :class="classes"
    v-bind="$attrs"
    class="mdc-button"
    v-on="$listeners"
  >
    <slot name="icon"/>
    <slot/>
  </button>
</template>

<script>
  import { MDCRipple } from '@material/ripple/index';

  export default {
    name: 'MButton',
    props: {
      raised: {
        type: Boolean,
        default: false,
      },
      unelevated: {
        type: Boolean,
        default: false,
      },
      outlined: {
        type: Boolean,
        default: false,
      },
      href: {
        type: String,
        default: '',
      },
    },
    computed: {
      classes() {
        return {
          'mdc-button--raised': this.raised,
          'mdc-button--unelevated': this.unelevated,
          'mdc-button--outlined': this.outlined,
        };
      },
    },
    mounted() {
      this.mdcRipple = MDCRipple.attachTo(this.$el);
    },
    beforeDestroy() {
      this.mdcRipple.destroy();
    },
  };
</script>

<style lang="scss">
  @import "~@material/button/mdc-button.scss";
</style>
